version: '3.3'

services:
  vscode:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "5.0"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        INSTALL_AZURE_CLI: "false"

    environment:
      ENVIRONMENT: "devcontainer"

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      #- "5000:5000/tcp"
      #- "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  seq:
    image: datalust/seq:latest
    environment:
    - ACCEPT_EULA=Y
    ports:
    #- "5341:5341"
    - "5080:80"
    restart: always
